CFILE  = funcionalidades.c arquivos.c registros.c main.c
HFILE = funcionalidades.h arquivos.h registros.h

all :
	gcc -g -o programaTrab $(CFILE) $(HFILE)

run : programaTrab
	./programaTrab

clean :
	rm *.o programaTrab